### ISSUE TITLE
Python 3.7.9: "SSL is not available" after installed pyssl

### ISSUE THREAD

**Issue by crash5** [sebageek/servefile#7]
When try to use `python -m servefile --ssl -l .` i always get `Error: SSL is not available, please install pyssl (python-openssl).`

After `apt install python-openssl` and `python -m pip install python-openssl` the error message is the same.

It looks like the `python -m pip install pyopenssl` is the working version.

Used the above commands in a container `docker run --rm -ti -v $PWD:/work/ python:3.7-slim /bin/bash`

\* The servefile still can't start because it has only the loopback interface, but the ssl looks good.

**Comment by sebageek** [comment]
`apt install python-openssl` works only for python2 unter debian. For python3 try using `apt install python3-openssl`. I'll change the debian packet name to its python3-pendant.
For `pyssl` - well, that's just completely wrong for using it with pip... so I'll change that to `pyopenssl`, as it was written in `setup.py`. Thanks for the report.
